-- Initial schema for the e-commerce order flow.
-- Matches the JPA entities in org.booleanuk.app.model.

CREATE TABLE customers (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE products (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255),
    price DOUBLE PRECISION NOT NULL
);

CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    customer_id  BIGINT,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE order_products (
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order_products_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_products_product FOREIGN KEY (product_id) REFERENCES products (id)
);
